project:
  type: website
  output-dir: quarto-build

version: "0.1.0"  
  

website:
  title: "shot"
  page-footer:
    center: "Documentation for release version **{{< meta version >}}**"

  navbar:
    left:
      - href: index.qmd
        text: Home
                 
    right:   
      - icon: github
        menu:
          - text: "Neel Smith home"
            href: https://neelsmith.github.io
          - text: "Links to some projects"
            href: https://neelsmith.github.io/projects 
   
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



